// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://spec` | (string & {});
};

/**
 * Ошибка с машинным кодом и сообщением для пользователя.
 */
export type ApiError = {
    code: 'not_found' | 'validation_error' | 'slot_unavailable' | 'already_exists';
    message: string;
};

/**
 * Встреча в календаре владельца.
 */
export type Booking = {
    id: string;
    eventTypeId: string;
    eventTypeTitle: string;
    start: string;
    end: string;
    guestName: string;
    guestEmail: string;
    createdAt: string;
};

/**
 * Данные гостя для записи на слот.
 */
export type BookingRequest = {
    eventTypeId: string;
    /**
     * Начало выбранного слота из списка свободных.
     */
    start: string;
    guestName: string;
    guestEmail: string;
};

/**
 * Тип встречи, который владелец календаря предлагает гостям.
 */
export type EventType = {
    /**
     * Идентификатор-слаг, задаёт владелец: `intro-call`.
     */
    id: string;
    title: string;
    description: string;
    /**
     * Длительность встречи: кратна 30 минутам, от 30 до 240.
     */
    durationMinutes: number;
};

/**
 * Свободный интервал для записи. Время в UTC.
 */
export type Slot = {
    start: string;
    end: string;
};

export type ListBookingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/bookings';
};

export type ListBookingsResponses = {
    /**
     * The request has succeeded.
     */
    200: Array<Booking>;
};

export type ListBookingsResponse = ListBookingsResponses[keyof ListBookingsResponses];

export type CreateBookingData = {
    body: BookingRequest;
    path?: never;
    query?: never;
    url: '/api/bookings';
};

export type CreateBookingErrors = {
    /**
     * The server cannot find the requested resource.
     */
    404: ApiError;
    /**
     * The request conflicts with the current state of the server.
     */
    409: ApiError;
    /**
     * Client error
     */
    422: ApiError;
};

export type CreateBookingError = CreateBookingErrors[keyof CreateBookingErrors];

export type CreateBookingResponses = {
    /**
     * The request has succeeded and a new resource has been created as a result.
     */
    201: Booking;
};

export type CreateBookingResponse = CreateBookingResponses[keyof CreateBookingResponses];

export type ListEventTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/event-types';
};

export type ListEventTypesResponses = {
    /**
     * The request has succeeded.
     */
    200: Array<EventType>;
};

export type ListEventTypesResponse = ListEventTypesResponses[keyof ListEventTypesResponses];

export type CreateEventTypeData = {
    body: EventType;
    path?: never;
    query?: never;
    url: '/api/event-types';
};

export type CreateEventTypeErrors = {
    /**
     * The request conflicts with the current state of the server.
     */
    409: ApiError;
    /**
     * Client error
     */
    422: ApiError;
};

export type CreateEventTypeError = CreateEventTypeErrors[keyof CreateEventTypeErrors];

export type CreateEventTypeResponses = {
    /**
     * The request has succeeded and a new resource has been created as a result.
     */
    201: EventType;
};

export type CreateEventTypeResponse = CreateEventTypeResponses[keyof CreateEventTypeResponses];

export type GetEventTypeData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/event-types/{id}';
};

export type GetEventTypeErrors = {
    /**
     * The server cannot find the requested resource.
     */
    404: ApiError;
};

export type GetEventTypeError = GetEventTypeErrors[keyof GetEventTypeErrors];

export type GetEventTypeResponses = {
    /**
     * The request has succeeded.
     */
    200: EventType;
};

export type GetEventTypeResponse = GetEventTypeResponses[keyof GetEventTypeResponses];

export type ListSlotsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/event-types/{id}/slots';
};

export type ListSlotsErrors = {
    /**
     * The server cannot find the requested resource.
     */
    404: ApiError;
};

export type ListSlotsError = ListSlotsErrors[keyof ListSlotsErrors];

export type ListSlotsResponses = {
    /**
     * The request has succeeded.
     */
    200: Array<Slot>;
};

export type ListSlotsResponse = ListSlotsResponses[keyof ListSlotsResponses];
